#!/bin/bash
fusermount -u fuse_c
mkdir build 2>&1 | grep -v "File exists"
cd build && cmake .. > /dev/null && make
cd ..
mkdir fuse_c 2>&1 | grep -v "File exists" || true
truncate --size=0 err.txt || true
build/fuse-example fuse_c -f --filename my_file --file-content 'JOJO' --size `pwd`/err.txt

